<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>impex</string>
		<string>csv</string>
	</array>
	<key>keyEquivalent</key>
	<string>@i</string>
	<key>name</key>
	<string>Impex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.impex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword.modifiers.impex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.impex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=UPDATE).*?(?=;)|(?&lt;=REMOVE).*?(?=;)|(?&lt;=REMOVE).*?(?=\[)|(?&lt;=UPDATE).*?(?=\[)</string>
			<key>name</key>
			<string>entity.impex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>storage.other.impex</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.impex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable.impex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>string.unquoted.modifier.impex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant.modifiers.impex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>string.other.parenthesis.impex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant.character.escape.untitled</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable.impex</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>constant.character.escape.untitled</key>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>constant.character.escape.untitled</string>
		</dict>
		<key>constant.modifiers.impex</key>
		<dict>
			<key>match</key>
			<string>\b(unique|default|translator|mode|processor|batchmode|cacheUnique|impex.legacy.mode|alias|allownull|cellDecorator|collection-delimiter|dateformat|forceWrite|ignoreKeyCase|ignoreNull|key2value-delimiter|lang|map-delimiter|numberformat|path-delimiter|virtual)\b</string>
			<key>name</key>
			<string>constant.modifiers.impex</string>
		</dict>
		<key>ignore.key</key>
		<dict>
			<key>match</key>
			<string>&lt;ignore&gt;</string>
			<key>name</key>
			<string>constant.ignore</string>
		</dict>
		<key>keyword.modifiers.impex</key>
		<dict>
			<key>match</key>
			<string>\b(INSERT_UPDATE|INSERT|UPDATE|REMOVE)\b</string>
			<key>name</key>
			<string>keyword.modifiers.impex</string>
		</dict>
		<key>variable.impex</key>
		<dict>
			<key>match</key>
			<string>\$\w+</string>
			<key>name</key>
			<string>variable.impex</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.impex</string>
	<key>uuid</key>
	<string>881E66B3-2A70-44E0-B178-374FD8ACA880</string>
</dict>
</plist>
